### ISSUE TITLE
fix MDI nerd icons

### ISSUE THREAD

**Issue by DaRandomCube** [HiDe-Techno-Tips/Acenoster-ZSH-Theme#2]
since MDI icons are deprecated and removed from nerd fonts, most of the icons show question marks and random Arabic letters
![image](https://github.com/HimDek/Acenoster-ZSH-Theme/assets/93283139/dde0e590-0061-482a-8361-1c28ac00a0ec)
latest commit was 2 weeks ago, but it's not related to the project, but to the website

**Comment by HimDek** [comment]
Fixed with 1792bf1. Thanks for the report. The deprecation of mdi fonts went unnoticed by me because I was using the older version of nerd fonts in my system.
